# ament_python template
%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^@(InstallationPrefix)/.*$
%global __requires_exclude_from ^@(InstallationPrefix)/.*$

Name:           @(Package)
Version:        @(Version)
Release:        @(RPMInc)%{?dist}%{?release_suffix}
Summary:        ROS @(Name) package

License:        @(License)
Group:          Development/Libraries
@[if Homepage and Homepage != '']URL:            @(Homepage)@\n@[end if]@
Source0:        @(Source0)
Source1:        ros-rpmlintrc
@{pc = -1}@[for p in Patches]@{pc = pc + 1}Patch@(pc):         @p@\n@[end for]@[if NoArch]@\nBuildArch:      noarch@\n@[end if]@

@[for p in Depends]Requires:       @p@\n@[end for]@

# Default BuildRequires Includes
BuildRequires:  python-rpm-macros
BuildRequires:  %{python_module pip}
BuildRequires:  fdupes

# Generated BuildRequires Includes - Start
@[for p in sorted(BuildDepends + ['%{python_module devel}'])]BuildRequires:  @p@\n@[end for]@
# Generated BuildRequires Includes - End

@[for p in Conflicts]Conflicts:      @p@\n@[end for]@
@[for p in Replaces]Obsoletes:      @p@\n@[end for]@

%description
@(Description)

%prep
%autosetup -p0 -n @(TarDirName)

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "@(InstallationPrefix)/setup.sh" ]; then . "@(InstallationPrefix)/setup.sh"; fi
%pyproject_wheel

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "@(InstallationPrefix)/setup.sh" ]; then . "@(InstallationPrefix)/setup.sh"; fi
%pyproject_install
%python_expand %fdupes %{buildroot}%{python_sitelib}
# For "Reasons", we have to manually move everything to %%{buildroot}@(InstallationPrefix)
# Atleast until we figure out an option to pyproject_install to install there in the first place.
mkdir -p %{buildroot}@(InstallationPrefix)
# Move %%{buildroot}%%{python_sitelib} packages
if [ -d %{buildroot}%{python_sitelib} ]; then mkdir -p %{buildroot}@(InstallationPrefix)%{python_sitelib}; mv %{buildroot}%{python_sitelib}/* %{buildroot}@(InstallationPrefix)%{python_sitelib}; fi
# Move %%{buildroot}%%{_datadir} packages
if [ -d %{buildroot}%{_datadir} ]; then mkdir -p %{buildroot}@(InstallationPrefix)%{_datadir}; mv %{buildroot}%{_datadir}/* %{buildroot}@(InstallationPrefix)%{_datadir}; fi

# Disable checks - For now.
%if 0
%check
# Look for a directory with a name indicating that it contains tests
TEST_TARGET=$(ls -d * | grep -m1 "\(test\|tests\)" ||:)
if [ -n "$TEST_TARGET" ] && %__python3 -m pytest --version; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "@(InstallationPrefix)/setup.sh" ]; then . "@(InstallationPrefix)/setup.sh"; fi
%__python3 -m pytest $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif

%files
@(InstallationPrefix)

%changelog@
@[for change_version, (change_date, main_name, main_email) in changelogs]
* @(change_date) @(main_name) <@(main_email)> - @(change_version)
- Autogenerated by Bloom
@[end for]
